services:
  postgres:
    image: postgres:16
    container_name: platformaai-postgres
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: platformaai
      POSTGRES_USER: platformaai
      POSTGRES_PASSWORD: platformaai
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: platformaai-pgadmin
    restart: unless-stopped
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@platforma.ai
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data:
