-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ORG_INVITE_RESENT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ORG_INVITE_ACCEPT_REJECTED_UNVERIFIED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ORG_INVITE_ACCEPT_RATE_LIMITED';

-- AlterTable
ALTER TABLE "User" ADD COLUMN "emailVerifiedByProvider" BOOLEAN;
